### PR TITLE
Add emitter.once support

### PR DESCRIPTION
**Pull request by Kikobeats**

### CODE REVIEW

**Comment by Kikobeats** [comment]
Well I can repair the test but first I want to know your opinion 🙂

**Comment by sindresorhus** [comment]
What problem is this solving?

**Comment by sindresorhus** [comment]
This is already handled by `p-event`: https://github.com/sindresorhus/p-event/blob/da59143760a36bcf9e3f309609c2ddf33c27c8bd/index.js#L51 It unsubscribes after the first event.

**Comment by Kikobeats** [comment]
Perfect, thanks for the clarification 🙂

**Pull request closed without merging**
